### ISSUE TITLE
Add an option to ping volunteers to share their location

### ISSUE THREAD

**Issue by Propo41** [Propo41/aust_travels#100]
After pinging, volunteers will receive a notification..

**Comment by SNNafi** [comment]
Is it something like push notifications i.e. FCM ?

**Comment by Propo41** [comment]
> Is it something like push notifications i.e. FCM ?

Yes. Although last time I checked, firebase FCM service was changed from free to paid. Probably there are other free APIs out there

**Comment by SNNafi** [comment]
No, it's always free. Unlimited. I have been using them in several production apps.

**Comment by Propo41** [comment]
Really? That's great then! Would you be willing to contribute to this feature provided that I build the UI?

**Comment by SNNafi** [comment]
Yes, brother. I can contribute inn sha Allah

**Comment by Propo41** [comment]
> Yes, brother. I can contribute in sha Allah

Thank you, brother! This will be a great addition to the app. You can contact me directly on Facebook. My profile can be found [here ](https://www.facebook.com/ahnaf.swapnil/)
