### ISSUE TITLE
user can share location without selecting time

### ISSUE THREAD

**Issue by tashfiq333** [Propo41/aust_travels#39]
![258905944_615447643208616_360200392420074288_n](https://user-images.githubusercontent.com/49322945/143241320-5d4cfebb-5edb-4ef9-92a3-050ee434e920.jpg)
![258867348_640743376942490_6674347303451258410_n](https://user-images.githubusercontent.com/49322945/143241327-57fe1405-bb6a-4fbc-b691-f4c6a889afd3.jpg)

**Comment by Propo41** [comment]
Was fixed
